#pragma once

#define PD_TYPE_0 "Reserved"
#define PD_TYPE_1 "GoodCRC"
#define PD_TYPE_2 "GotoMin"
#define PD_TYPE_3 "Accept"
#define PD_TYPE_4 "Reject"
#define PD_TYPE_5 "Ping"
#define PD_TYPE_6 "PS_RDY"
#define PD_TYPE_7 "Get_Source_Cap"
#define PD_TYPE_8 "Get_Sink_Cap"
#define PD_TYPE_9 "DR_Swap"
#define PD_TYPE_10 "PR_Swap"
#define PD_TYPE_11 "VCONN_Swap"
#define PD_TYPE_12 "Wait"
#define PD_TYPE_13 "Soft_Reset"
#define PD_TYPE_14 "Data_Reset"
#define PD_TYPE_15 "Data_Reset_Complete"