name: CMake

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  pull_request_target:
    branches: [ "development" ]
  workflow_dispatch:
  
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    #Global Setup
    - name: Checkout PD2Breadboard
      uses: actions/checkout@v3
      
    - name: Setup SDK pipeline
      uses: Fortinbra/RaspberryPiPicoBuild@v1
    
    - name: Checkout submodules
      working-directory: ${{github.workspace}}
      run: git submodule update --init
    
    - name: Get core count
      id: core_count
      run : cat /proc/cpuinfo  | grep processor | wc -l
      #End Global Setup
      
    - name: Setup PD2Breadboard
      working-directory: ./Software

    - name: Pico Build Configure CMake
      shell: bash
      run: PICO_SDK_PATH=${{github.workspace}}/pico-sdk SKIP_WEBBUILD=TRUE cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Pico Build
      shell: bash
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel ${{steps.core_count.outputs.output}}
 
